# coding: utf-8

"""
    Forza Open API

    API REST ouverte, gratuite et communautaire pour les données Forza Horizon (FH6 d'abord, FH5 en backfill). Contract-first : ce fichier est la source de vérité ; le serveur Go (ogen) et les clients TS en découlent. Champ `game` partout (game-agnostic). Erreurs en RFC 9457. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CarObtainMasteryUnlock(BaseModel):
    """
    Perk Car Mastery d'une autre voiture qui débloque cette voiture (effectType car_unlock). 
    """ # noqa: E501
    perk_id: StrictStr = Field(description="Identifiant de la perk (réf. /v1/cars/{id}/mastery).", alias="perkId")
    owner_car_id: StrictStr = Field(description="Voiture dont l'arbre contient la perk (réf. /v1/cars).", alias="ownerCarId")
    perk_name: Optional[StrictStr] = Field(default=None, alias="perkName")
    __properties: ClassVar[List[str]] = ["perkId", "ownerCarId", "perkName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CarObtainMasteryUnlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CarObtainMasteryUnlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "perkId": obj.get("perkId"),
            "ownerCarId": obj.get("ownerCarId"),
            "perkName": obj.get("perkName")
        })
        return _obj


