# coding: utf-8

"""
    Forza Open API

    API REST ouverte, gratuite et communautaire pour les données Forza Horizon (FH6 d'abord, FH5 en backfill). Contract-first : ce fichier est la source de vérité ; le serveur Go (ogen) et les clients TS en découlent. Champ `game` partout (game-agnostic). Erreurs en RFC 9457. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from forza_open_api_client.models.event_type import EventType
from forza_open_api_client.models.game import Game
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Event(BaseModel):
    """
    Événement / course (route fixe ou circuit).
    """ # noqa: E501
    id: StrictStr
    game: Game
    name: StrictStr
    type: EventType
    region: Optional[StrictStr] = Field(default=None, description="Région de la carte (dépend du jeu ; FH6 = 7 régions / 74 districts). Valeur libre : l'ensemble n'est pas figé au contrat. Absente → champ omis. ")
    start_lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="startLat")
    start_lng: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="startLng")
    end_lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="endLat")
    end_lng: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="endLng")
    route_geojson: Optional[Dict[str, Any]] = Field(default=None, description="Tracé GeoJSON (LineString) si disponible.", alias="routeGeojson")
    car_class_restriction: Optional[StrictStr] = Field(default=None, alias="carClassRestriction")
    length_m: Optional[StrictInt] = Field(default=None, alias="lengthM")
    __properties: ClassVar[List[str]] = ["id", "game", "name", "type", "region", "startLat", "startLng", "endLat", "endLng", "routeGeojson", "carClassRestriction", "lengthM"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "game": obj.get("game"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "region": obj.get("region"),
            "startLat": obj.get("startLat"),
            "startLng": obj.get("startLng"),
            "endLat": obj.get("endLat"),
            "endLng": obj.get("endLng"),
            "routeGeojson": obj.get("routeGeojson"),
            "carClassRestriction": obj.get("carClassRestriction"),
            "lengthM": obj.get("lengthM")
        })
        return _obj


