# coding: utf-8

"""
    Forza Open API

    API REST ouverte, gratuite et communautaire pour les données Forza Horizon (FH6 d'abord, FH5 en backfill). Contract-first : ce fichier est la source de vérité ; le serveur Go (ogen) et les clients TS en découlent. Champ `game` partout (game-agnostic). Erreurs en RFC 9457. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Me(BaseModel):
    """
    Identité et quota de la clé API présentée dans X-API-Key (endpoint /v1/me, authentification requise). remaining/resetAt reflètent l'état courant de la fenêtre glissante de rate-limit (cohérents avec les en-têtes X-RateLimit-* de la réponse) ; tous deux omis si le compteur (Redis) est indisponible. 
    """ # noqa: E501
    name: StrictStr = Field(description="Nom de la clé (libellé donné à la création).")
    scopes: List[StrictStr] = Field(description="Permissions accordées à la clé (ex. read, submit-ugc).")
    rate_limit: StrictInt = Field(description="Quota maximal de requêtes sur la fenêtre glissante.", alias="rateLimit")
    remaining: Optional[StrictInt] = Field(default=None, description="Requêtes restantes sur la fenêtre courante (compteur sliding-window). Omis si le compteur (Redis) est indisponible. ")
    reset_at: Optional[datetime] = Field(default=None, description="Instant où un créneau de quota se libère (fin de la fenêtre courante). Omis si le compteur (Redis) est indisponible. ", alias="resetAt")
    created_at: datetime = Field(description="Date de création de la clé.", alias="createdAt")
    __properties: ClassVar[List[str]] = ["name", "scopes", "rateLimit", "remaining", "resetAt", "createdAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Me from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Me from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "scopes": obj.get("scopes"),
            "rateLimit": obj.get("rateLimit"),
            "remaining": obj.get("remaining"),
            "resetAt": obj.get("resetAt"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


