# coding: utf-8

"""
    Forza Open API

    API REST ouverte, gratuite et communautaire pour les données Forza Horizon (FH6 d'abord, FH5 en backfill). Contract-first : ce fichier est la source de vérité ; le serveur Go (ogen) et les clients TS en découlent. Champ `game` partout (game-agnostic). Erreurs en RFC 9457. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from forza_open_api_client.models.game import Game
from forza_open_api_client.models.upgrade_part_category import UpgradePartCategory
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpgradePart(BaseModel):
    """
    Pièce du catalogue d'upgrade (générique, indépendante d'une voiture). Les deltas sont relatifs au palier inférieur ; NULL si non sourcés (précision > exhaustivité). Sourcing progressif : voitures populaires d'abord, extension par séries ensuite. 
    """ # noqa: E501
    id: StrictStr
    game: Game
    category: UpgradePartCategory
    name: StrictStr
    level: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Palier de la pièce (1 = premier niveau). Omis si non applicable.")
    pi_delta: Optional[StrictInt] = Field(default=None, description="Variation de Performance Index apportée par la pièce.", alias="piDelta")
    weight_delta_kg: Optional[StrictInt] = Field(default=None, description="Variation de poids (kg). Négatif = allègement.", alias="weightDeltaKg")
    power_delta_hp: Optional[StrictInt] = Field(default=None, description="Variation de puissance (ch).", alias="powerDeltaHp")
    torque_delta_nm: Optional[StrictInt] = Field(default=None, description="Variation de couple (Nm).", alias="torqueDeltaNm")
    source: Optional[StrictStr] = Field(default=None, description="Source propre de la donnée.")
    last_verified: Optional[datetime] = Field(default=None, alias="lastVerified")
    __properties: ClassVar[List[str]] = ["id", "game", "category", "name", "level", "piDelta", "weightDeltaKg", "powerDeltaHp", "torqueDeltaNm", "source", "lastVerified"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpgradePart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpgradePart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "game": obj.get("game"),
            "category": obj.get("category"),
            "name": obj.get("name"),
            "level": obj.get("level"),
            "piDelta": obj.get("piDelta"),
            "weightDeltaKg": obj.get("weightDeltaKg"),
            "powerDeltaHp": obj.get("powerDeltaHp"),
            "torqueDeltaNm": obj.get("torqueDeltaNm"),
            "source": obj.get("source"),
            "lastVerified": obj.get("lastVerified")
        })
        return _obj


