// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CompareCarsOperation        OperationName = "CompareCars"
	GetBarnFindOperation        OperationName = "GetBarnFind"
	GetCarOperation             OperationName = "GetCar"
	GetCarMasteryOperation      OperationName = "GetCarMastery"
	GetCarObtainOperation       OperationName = "GetCarObtain"
	GetCurrentPlaylistOperation OperationName = "GetCurrentPlaylist"
	GetDlcPackOperation         OperationName = "GetDlcPack"
	GetEventOperation           OperationName = "GetEvent"
	GetMetaOperation            OperationName = "GetMeta"
	GetPrStuntOperation         OperationName = "GetPrStunt"
	GetRandomCarOperation       OperationName = "GetRandomCar"
	GetRandomTrackOperation     OperationName = "GetRandomTrack"
	GetReferenceOperation       OperationName = "GetReference"
	GetSeriesOperation          OperationName = "GetSeries"
	GetTrackOperation           OperationName = "GetTrack"
	GetTreasureCarOperation     OperationName = "GetTreasureCar"
	ListBarnFindsOperation      OperationName = "ListBarnFinds"
	ListCarUpgradesOperation    OperationName = "ListCarUpgrades"
	ListCarsOperation           OperationName = "ListCars"
	ListChangesOperation        OperationName = "ListChanges"
	ListDlcPacksOperation       OperationName = "ListDlcPacks"
	ListEventsOperation         OperationName = "ListEvents"
	ListJournalTiersOperation   OperationName = "ListJournalTiers"
	ListManufacturersOperation  OperationName = "ListManufacturers"
	ListPrStuntsOperation       OperationName = "ListPrStunts"
	ListSeriesOperation         OperationName = "ListSeries"
	ListStoriesOperation        OperationName = "ListStories"
	ListToursOperation          OperationName = "ListTours"
	ListTracksOperation         OperationName = "ListTracks"
	ListTreasureCarsOperation   OperationName = "ListTreasureCars"
	ListUpgradePartsOperation   OperationName = "ListUpgradeParts"
	SearchOperation             OperationName = "Search"
)
