// Code generated by ogen, DO NOT EDIT.
package oas

type GetCarMasteryRes interface {
	getCarMasteryRes()
}

type GetCarRes interface {
	getCarRes()
}

type GetCurrentPlaylistRes interface {
	getCurrentPlaylistRes()
}

type GetReferenceRes interface {
	getReferenceRes()
}

type GetSeriesRes interface {
	getSeriesRes()
}

type ListBarnFindsRes interface {
	listBarnFindsRes()
}

type ListCarUpgradesRes interface {
	listCarUpgradesRes()
}

type ListCarsRes interface {
	listCarsRes()
}

type ListDlcPacksRes interface {
	listDlcPacksRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListJournalTiersRes interface {
	listJournalTiersRes()
}

type ListManufacturersRes interface {
	listManufacturersRes()
}

type ListPrStuntsRes interface {
	listPrStuntsRes()
}

type ListSeriesRes interface {
	listSeriesRes()
}

type ListTracksRes interface {
	listTracksRes()
}

type ListTreasureCarsRes interface {
	listTreasureCarsRes()
}

type ListUpgradePartsRes interface {
	listUpgradePartsRes()
}
