// Code generated by ogen, DO NOT EDIT.
package oas

type CompareCarsRes interface {
	compareCarsRes()
}

type GetBarnFindRes interface {
	getBarnFindRes()
}

type GetCarMasteryRes interface {
	getCarMasteryRes()
}

type GetCarObtainRes interface {
	getCarObtainRes()
}

type GetCarRes interface {
	getCarRes()
}

type GetCurrentPlaylistRes interface {
	getCurrentPlaylistRes()
}

type GetDlcPackRes interface {
	getDlcPackRes()
}

type GetEventRes interface {
	getEventRes()
}

type GetForzathonShopRes interface {
	getForzathonShopRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetMetaRes interface {
	getMetaRes()
}

type GetPrStuntRes interface {
	getPrStuntRes()
}

type GetRandomCarRes interface {
	getRandomCarRes()
}

type GetRandomTrackRes interface {
	getRandomTrackRes()
}

type GetReferenceRes interface {
	getReferenceRes()
}

type GetSeriesRes interface {
	getSeriesRes()
}

type GetTrackRes interface {
	getTrackRes()
}

type GetTreasureCarRes interface {
	getTreasureCarRes()
}

type ListBarnFindsRes interface {
	listBarnFindsRes()
}

type ListCarUpgradesRes interface {
	listCarUpgradesRes()
}

type ListCarsRes interface {
	listCarsRes()
}

type ListChangesRes interface {
	listChangesRes()
}

type ListDlcPacksRes interface {
	listDlcPacksRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListExportsRes interface {
	listExportsRes()
}

type ListForzathonShopHistoryRes interface {
	listForzathonShopHistoryRes()
}

type ListJournalTiersRes interface {
	listJournalTiersRes()
}

type ListManufacturersRes interface {
	listManufacturersRes()
}

type ListPrStuntsRes interface {
	listPrStuntsRes()
}

type ListSeriesRes interface {
	listSeriesRes()
}

type ListStoriesRes interface {
	listStoriesRes()
}

type ListToursRes interface {
	listToursRes()
}

type ListTracksRes interface {
	listTracksRes()
}

type ListTreasureCarsRes interface {
	listTreasureCarsRes()
}

type ListUpgradePartsRes interface {
	listUpgradePartsRes()
}

type SearchRes interface {
	searchRes()
}
