// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCarOperation             OperationName = "GetCar"
	GetCarMasteryOperation      OperationName = "GetCarMastery"
	GetCurrentPlaylistOperation OperationName = "GetCurrentPlaylist"
	GetRandomCarOperation       OperationName = "GetRandomCar"
	GetReferenceOperation       OperationName = "GetReference"
	GetSeriesOperation          OperationName = "GetSeries"
	ListBarnFindsOperation      OperationName = "ListBarnFinds"
	ListCarUpgradesOperation    OperationName = "ListCarUpgrades"
	ListCarsOperation           OperationName = "ListCars"
	ListDlcPacksOperation       OperationName = "ListDlcPacks"
	ListEventsOperation         OperationName = "ListEvents"
	ListJournalTiersOperation   OperationName = "ListJournalTiers"
	ListManufacturersOperation  OperationName = "ListManufacturers"
	ListPrStuntsOperation       OperationName = "ListPrStunts"
	ListSeriesOperation         OperationName = "ListSeries"
	ListTracksOperation         OperationName = "ListTracks"
	ListTreasureCarsOperation   OperationName = "ListTreasureCars"
	ListUpgradePartsOperation   OperationName = "ListUpgradeParts"
)
