// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	BarnFindsHandler
	CarsHandler
	DLCHandler
	EventsHandler
	ManufacturersHandler
	MasteryHandler
	PRStuntsHandler
	PlaylistHandler
	TracksHandler
	TreasureCarsHandler
	UpgradesHandler
}

// BarnFindsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: BarnFinds
type BarnFindsHandler interface {
	// ListBarnFinds implements listBarnFinds operation.
	//
	// Liste les Barn Finds (épaves cachées à trouver puis restaurer).
	//
	// GET /v1/barn-finds
	ListBarnFinds(ctx context.Context, params ListBarnFindsParams) (ListBarnFindsRes, error)
}

// CarsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Cars
type CarsHandler interface {
	// GetCar implements getCar operation.
	//
	// Récupère une voiture par identifiant.
	//
	// GET /v1/cars/{id}
	GetCar(ctx context.Context, params GetCarParams) (GetCarRes, error)
	// ListCars implements listCars operation.
	//
	// Liste les voitures du catalogue.
	//
	// GET /v1/cars
	ListCars(ctx context.Context, params ListCarsParams) (ListCarsRes, error)
}

// DLCHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: DLC
type DLCHandler interface {
	// ListDlcPacks implements listDlcPacks operation.
	//
	// Liste les packs DLC / extensions d'un jeu.
	//
	// GET /v1/dlc-packs
	ListDlcPacks(ctx context.Context, params ListDlcPacksParams) (ListDlcPacksRes, error)
}

// EventsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Events
type EventsHandler interface {
	// ListEvents implements listEvents operation.
	//
	// Liste les événements / courses.
	//
	// GET /v1/events
	ListEvents(ctx context.Context, params ListEventsParams) (ListEventsRes, error)
}

// ManufacturersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Manufacturers
type ManufacturersHandler interface {
	// ListManufacturers implements listManufacturers operation.
	//
	// Liste les constructeurs.
	//
	// GET /v1/manufacturers
	ListManufacturers(ctx context.Context, params ListManufacturersParams) (ListManufacturersRes, error)
}

// MasteryHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Mastery
type MasteryHandler interface {
	// GetCarMastery implements getCarMastery operation.
	//
	// Perks de l'arbre Car Mastery FH6 de la voiture. Chaque perk occupe une case (row, col) de la
	// grille 4×4, coûte des Skill Points (spCost), peut dépendre d'une autre (prereqPerkId) et
	// certaines débloquent une voiture cachée (effectType car_unlock → unlockedCarId). Le jeu est
	// déterminé par la voiture. Voiture inconnue ou arbre non sourcé → liste vide.
	//
	// GET /v1/cars/{id}/mastery
	GetCarMastery(ctx context.Context, params GetCarMasteryParams) (GetCarMasteryRes, error)
}

// PRStuntsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: PRStunts
type PRStuntsHandler interface {
	// ListPrStunts implements listPrStunts operation.
	//
	// Liste les PR Stunts (speed trap, speed zone, drift zone, danger sign).
	//
	// GET /v1/pr-stunts
	ListPrStunts(ctx context.Context, params ListPrStuntsParams) (ListPrStuntsRes, error)
}

// PlaylistHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Playlist
type PlaylistHandler interface {
	// GetCurrentPlaylist implements getCurrentPlaylist operation.
	//
	// Festival Playlist courante d'un jeu.
	//
	// GET /v1/playlist/current
	GetCurrentPlaylist(ctx context.Context, params GetCurrentPlaylistParams) (GetCurrentPlaylistRes, error)
	// GetSeries implements getSeries operation.
	//
	// Récupère une série par identifiant.
	//
	// GET /v1/playlist/series/{id}
	GetSeries(ctx context.Context, params GetSeriesParams) (GetSeriesRes, error)
	// ListSeries implements listSeries operation.
	//
	// Liste les séries de Festival Playlist.
	//
	// GET /v1/playlist/series
	ListSeries(ctx context.Context, params ListSeriesParams) (ListSeriesRes, error)
}

// TracksHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Tracks
type TracksHandler interface {
	// ListTracks implements listTracks operation.
	//
	// Liste les tracés / circuits indexés.
	//
	// GET /v1/tracks
	ListTracks(ctx context.Context, params ListTracksParams) (ListTracksRes, error)
}

// TreasureCarsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: TreasureCars
type TreasureCarsHandler interface {
	// ListTreasureCars implements listTreasureCars operation.
	//
	// Liste les Treasure Cars (voitures liées aux postcards).
	//
	// GET /v1/treasure-cars
	ListTreasureCars(ctx context.Context, params ListTreasureCarsParams) (ListTreasureCarsRes, error)
}

// UpgradesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Upgrades
type UpgradesHandler interface {
	// ListCarUpgrades implements listCarUpgrades operation.
	//
	// Pièces d'upgrade montables sur la voiture, avec leurs contraintes d'installation (prérequis,
	// groupe exclusif). Le jeu est déterminé par la voiture (pas de paramètre game). Voiture inconnue
	// ou sans upgrade sourcé → page vide.
	//
	// GET /v1/cars/{id}/upgrades
	ListCarUpgrades(ctx context.Context, params ListCarUpgradesParams) (ListCarUpgradesRes, error)
	// ListUpgradeParts implements listUpgradeParts operation.
	//
	// Catalogue global des pièces d'upgrade.
	//
	// GET /v1/upgrade-parts
	ListUpgradeParts(ctx context.Context, params ListUpgradePartsParams) (ListUpgradePartsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
