// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCarOperation             OperationName = "GetCar"
	GetCurrentPlaylistOperation OperationName = "GetCurrentPlaylist"
	GetSeriesOperation          OperationName = "GetSeries"
	ListCarsOperation           OperationName = "ListCars"
	ListManufacturersOperation  OperationName = "ListManufacturers"
	ListSeriesOperation         OperationName = "ListSeries"
)
