// Code generated by ogen, DO NOT EDIT.
package oas

type GetCarRes interface {
	getCarRes()
}

type GetCurrentPlaylistRes interface {
	getCurrentPlaylistRes()
}

type GetSeriesRes interface {
	getSeriesRes()
}

type ListCarsRes interface {
	listCarsRes()
}

type ListDlcPacksRes interface {
	listDlcPacksRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListManufacturersRes interface {
	listManufacturersRes()
}

type ListPrStuntsRes interface {
	listPrStuntsRes()
}

type ListSeriesRes interface {
	listSeriesRes()
}

type ListTracksRes interface {
	listTracksRes()
}
