// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	CarsHandler
	ManufacturersHandler
	PlaylistHandler
}

// CarsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Cars
type CarsHandler interface {
	// GetCar implements getCar operation.
	//
	// Récupère une voiture par identifiant.
	//
	// GET /v1/cars/{id}
	GetCar(ctx context.Context, params GetCarParams) (GetCarRes, error)
	// ListCars implements listCars operation.
	//
	// Liste les voitures du catalogue.
	//
	// GET /v1/cars
	ListCars(ctx context.Context, params ListCarsParams) (ListCarsRes, error)
}

// ManufacturersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Manufacturers
type ManufacturersHandler interface {
	// ListManufacturers implements listManufacturers operation.
	//
	// Liste les constructeurs.
	//
	// GET /v1/manufacturers
	ListManufacturers(ctx context.Context, params ListManufacturersParams) (ListManufacturersRes, error)
}

// PlaylistHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Playlist
type PlaylistHandler interface {
	// GetCurrentPlaylist implements getCurrentPlaylist operation.
	//
	// Festival Playlist courante d'un jeu.
	//
	// GET /v1/playlist/current
	GetCurrentPlaylist(ctx context.Context, params GetCurrentPlaylistParams) (GetCurrentPlaylistRes, error)
	// GetSeries implements getSeries operation.
	//
	// Récupère une série par identifiant.
	//
	// GET /v1/playlist/series/{id}
	GetSeries(ctx context.Context, params GetSeriesParams) (GetSeriesRes, error)
	// ListSeries implements listSeries operation.
	//
	// Liste les séries de Festival Playlist.
	//
	// GET /v1/playlist/series
	ListSeries(ctx context.Context, params ListSeriesParams) (ListSeriesRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
