"""
    Forza Open API

    API REST ouverte, gratuite et communautaire pour les données Forza Horizon (FH6 d'abord, FH5 en backfill). Contract-first : ce fichier est la source de vérité ; le serveur Go (ogen) et les clients TS en découlent. Champ `game` partout (game-agnostic). Erreurs en RFC 9457. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field
from typing import List, Optional
from typing_extensions import Annotated
from forza_open_api_client.models.game import Game
from forza_open_api_client.models.journal_tier import JournalTier
from forza_open_api_client.models.journal_track import JournalTrack

from forza_open_api_client.api_client import ApiClient, RequestSerialized
from forza_open_api_client.api_response import ApiResponse
from forza_open_api_client.rest import RESTResponseType


class JournalApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_journal_tiers(
        self,
        game: Annotated[Game, Field(description="Jeu cible (obligatoire sur les ressources multi-jeux).")],
        track: Annotated[Optional[JournalTrack], Field(description="Filtre par piste de progression.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[JournalTier]:
        """Liste les paliers du Collection Journal (wristbands + stamps).

        Paliers de progression du Collection Journal FH6 : 7 Wristbands (track horizon_festival, Yellow → Gold ; Gold débloque Legend Island + The Goliath) et 7 Stamps (track discover_japan, Visitor → Master Explorer ; poussent les Barn Finds). 17 voitures ne sont débloquables que via les rewardCarId de ces paliers. Remplace les Accolades de FH5. Ensemble borné (≤ 14 par jeu) → pas de pagination. 

        :param game: Jeu cible (obligatoire sur les ressources multi-jeux). (required)
        :type game: Game
        :param track: Filtre par piste de progression.
        :type track: JournalTrack
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_journal_tiers_serialize(
            game=game,
            track=track,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[JournalTier]",
            '400': "Error",
            '401': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_journal_tiers_with_http_info(
        self,
        game: Annotated[Game, Field(description="Jeu cible (obligatoire sur les ressources multi-jeux).")],
        track: Annotated[Optional[JournalTrack], Field(description="Filtre par piste de progression.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[JournalTier]]:
        """Liste les paliers du Collection Journal (wristbands + stamps).

        Paliers de progression du Collection Journal FH6 : 7 Wristbands (track horizon_festival, Yellow → Gold ; Gold débloque Legend Island + The Goliath) et 7 Stamps (track discover_japan, Visitor → Master Explorer ; poussent les Barn Finds). 17 voitures ne sont débloquables que via les rewardCarId de ces paliers. Remplace les Accolades de FH5. Ensemble borné (≤ 14 par jeu) → pas de pagination. 

        :param game: Jeu cible (obligatoire sur les ressources multi-jeux). (required)
        :type game: Game
        :param track: Filtre par piste de progression.
        :type track: JournalTrack
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_journal_tiers_serialize(
            game=game,
            track=track,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[JournalTier]",
            '400': "Error",
            '401': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_journal_tiers_without_preload_content(
        self,
        game: Annotated[Game, Field(description="Jeu cible (obligatoire sur les ressources multi-jeux).")],
        track: Annotated[Optional[JournalTrack], Field(description="Filtre par piste de progression.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Liste les paliers du Collection Journal (wristbands + stamps).

        Paliers de progression du Collection Journal FH6 : 7 Wristbands (track horizon_festival, Yellow → Gold ; Gold débloque Legend Island + The Goliath) et 7 Stamps (track discover_japan, Visitor → Master Explorer ; poussent les Barn Finds). 17 voitures ne sont débloquables que via les rewardCarId de ces paliers. Remplace les Accolades de FH5. Ensemble borné (≤ 14 par jeu) → pas de pagination. 

        :param game: Jeu cible (obligatoire sur les ressources multi-jeux). (required)
        :type game: Game
        :param track: Filtre par piste de progression.
        :type track: JournalTrack
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_journal_tiers_serialize(
            game=game,
            track=track,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[JournalTier]",
            '400': "Error",
            '401': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_journal_tiers_serialize(
        self,
        game,
        track,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if game is not None:
            
            _query_params.append(('game', game.value))
            
        if track is not None:
            
            _query_params.append(('track', track.value))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/journal',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


